<?php

/**
 * @file
 * Contains add_css.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function add_css_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the add_css module.
    case 'help.page.add_css':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Adding css through this module.') . '</p>';
      return $output;

    default:
  }
}

function add_css_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'add_css/add_css';
}

/**
 * Implements hook_theme().
 */
function add_css_theme() {
  $theme = [];

  return $theme;
}
